server:
  port: 8080
  address: 0.0.0.0
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Vinfast_db
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    password: root
    username: root
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-3-flash-preview
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB       # Dung lượng tối đa của 1 file
      max-request-size: 50MB    # Tổng dung lượng tối đa của 1 request (nhiều file)
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600
  refreshable-duration: 36000

# VNPAY Config
vnp:
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  tmnCode: "JPXWTQ76"
  hashSecret: "PST34F8S69Q185RFA4TV6JASTSRSK2RC"
  apiUrl: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
  returnUrl: http://localhost:3000/payment-callback