@startuml


start
:Nhấn "Mua trả góp" từ AI gợi ý;
:Chọn thông số (Pin, Tiền trả trước, Kỳ hạn, Ngân hàng);
:Hệ thống tính toán gốc và lãi;

repeat
  :Nhập thông tin cá nhân & Số CCCD;
  :Chọn Showroom nhận xe;
backward :Yêu cầu kiểm tra lại thông tin;
repeat while (Thông tin hợp lệ?) is (Không) not (Có)

:Hệ thống tạo hợp đồng điện tử;
:Khách hàng ký tên trên màn hình;


    :Hiển thị mã QR đặt cọc (50 triệu);
    if (Thanh toán thành công?) then (Có)
        :Hệ thống cập nhật trạng thái đơn hàng;
        :Tự động giữ xe trong kho (Gán số VIN);
        :Gửi thông báo xác nhận thành công;
        stop
    else (Không/Hủy)
        :Thông báo thanh toán thất bại;
        :Quay lại bước chọn phương thức thanh toán;
        detach
    endif

@enduml